### ISSUE TITLE
CORS Problem in API

### ISSUE THREAD

**Issue by onurcanozovali** [nickypangers/passport-visa-api#14]
When I send a request to the API via browser, I get a CORS error. However, when I send a GET request with Postman, it returns the response without any problems.

**Comment by onurcanozovali** [comment]
Thank you 🙌🙌

**Comment by nickypangers** [comment]
youre welcome. let me know if it works. if not this issue will be reopened. Thanks.

**Comment by onurcanozovali** [comment]
> youre welcome. let me know if it works. if not this issue will be reopened. Thanks.

![image](https://github.com/user-attachments/assets/5917ac16-7739-418c-a8af-6649441f50e8)

I tried again after your solution but I get the same error again.

But it works like this

![image](https://github.com/user-attachments/assets/cc20ab7d-f790-4cf1-9f85-28aa457d59a8)

**Comment by nickypangers** [comment]
It should now work on all routes. I've deployed a fix. I'll close this issue for now. Please let me know if you still encounter the same problem.
