### ISSUE TITLE
Cannot query visa information

### ISSUE THREAD

**Issue by ImranArtwel** [nickypangers/passport-visa-api#16]
The example url in the readme https://rough-sun-2523.fly.dev/country/GB does not return any response. In fact it returns a 502 error.
![Screenshot 2024-12-19 at 07 56 54](https://github.com/user-attachments/assets/c685aff2-8ac4-4b6e-bf1f-6b7250c7be9a)

**Comment by nickypangers** [comment]
Let me have a look. Thanks.

**Comment by nickypangers** [comment]
i've redeployed the api. it is working now from my end. please reopen this if it still doesn't work for you. thanks.
