### ISSUE TITLE
Incorrect API results

### ISSUE THREAD

**Issue by MuluhGodson** [nickypangers/passport-visa-api#8]
@nickypangers Hello, I noticed some of the data gotten from the API is incorrect. For instance:

`https://rough-sun-2523.fly.dev/api/us/ca`

returns the data

```json
{
    "passport": "US",
    "destination": "CA",
    "dur": "",
    "status": "VR",
    "category": "visa required",
    "last_updated": "2024-08-08T00:43:15.429384",
    "error": {
        "status": false,
        "error": ""
    }
}
```

which is false as US citizens can enter Canada without requiring a Visa.

Where is the base data pulled from and can it be easily corrected?

 [Passport Index](https://www.passportindex.org) seems to contain the latest up-to-date data but for some reason the API calls to the endpoints on Passport Index return the same errorneous data (I am using postman).
 
 I found this other website:
 
 - All Countries: https://api.henleypassportindex.com/api/v3/countries
 - Single Country: https://api.henleypassportindex.com/api/v3/visa-single/US
 
 Both return JSON

**Comment by nickypangers** [comment]
Thanks for noticing. The other APIs you provided does not give the detailed visa durations like the one used. Im encountering the same erroneous data as well. I'll leave this open and investigate for now.

**Comment by MuluhGodson** [comment]
Okay great. Let me know how I can be of assistance so we find a solution in
the time.

**Comment by ToastSeagers** [comment]
Similar error with za/bw. South African passport holders do not need a visa for Botswana.

**Comment by nickypangers** [comment]
Im guessing i could set up a firebase database to store data of each country then can have the community to verify data. however that can take a while since I've been occupied with work at the moment. Re @MuluhGodson :  https://api.henleypassportindex.com/api/v3/visa-single/US this api provides only accurate visa status but does not provide visa required information such as days. I'm not sure if the api im using and the one provided are complimentary.

**Comment by MuluhGodson** [comment]
A Firebase database will be great. If the information can be verified by the community, we can indeed add more info, such as visa procedures for each visa sourced from the official embassy websites (since it varies from country to country).

**Comment by nickypangers** [comment]
I just deployed a new version which fetch data from a postgres database i created just now.

I've added id into the visa queries.

If there are any inaccuracies feel free to open an issue with the id and the correct data so I can update accordingly.

Data structure has been changed as well btw.
